apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-service-deployment
  labels:
    app: nginx-with-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-with-service
  template:
    metadata:
      labels:
        app: nginx-with-service
    spec:
      containers:
      - name: nginx
        image: nginx:1.29.0
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "100m"